version: '2'

services:
  mariadb:
    tty: true
    environment:
      # MARIADB_DATABASE does not support multiple databases (for creation).
      #   Prefere creating one single DB for each bot, via the initdb into db/*.sql
      # - MARIADB_DATABASE="do-not-set-me"
      # set default credentials
      - MARIADB_ROOT_USER=mysql_root
      - MARIADB_ROOT_PASSWORD=mysql_pass
    build:
      context: .
      dockerfile: Dockerfile-mariadb
    volumes:
      - ./var/mysql:/bitnami/mariadb
      - ./db:/docker-entrypoint-initdb.d

  express:
    tty: true # Enables debugging capabilities when attached to this container.
    environment:
      - PORT=3000
      - NODE_ENV=development
      # - APP_DATABASE_URL=mysql://mysql_root:mysql_pass@mariadb/odiometro
      # - APP_BOT_NAME=${APP_BOT_NAME}
      - APP_DATABASE_NAME=${APP_BOT_NAME}
      - APP_DATABASE_HOST=mariadb
      - APP_DATABASE_USER=mysql_root
      - APP_DATABASE_PASSWORD=mysql_pass
      # Skip fetching dependencies and database migrations for production image
      - SKIP_DB_WAIT=0
      - SKIP_DB_MIGRATION=0
      # enable/disable features
      - SKIP_NPM_INSTALL=0
      - SKIP_BOWER_INSTALL=1
      - SKIP_SAMPLE_CODE=1
    build: .
    depends_on:
      - mariadb
    ports:
      - 3000:3000
    volumes:
      - .:/app
