version: '2'

services:
  mariadb:
    tty: true
    image: 'docker.io/bitnami/mariadb:10.3-debian-10'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_DATABASE=odiometro
      # set default credentials
      - MARIADB_ROOT_USER=mysql_root
      - MARIADB_ROOT_PASSWORD=mysql_pass
    volumes:
      - ./db/odiometro.sql:/docker-entrypoint-initdb.d
      - ./mysql:/var/lib/mysql
    build:
      context: .
      dockerfile: Dockerfile-mariadb
    #command: mysql -u mysql_root -p "mysql_pass" < /db/odiometro.sql

  express:
    tty: true # Enables debugging capabilities when attached to this container.
    image: docker.io/bitnami/express:4-debian-10
    environment:
      - PORT=3000
      - NODE_ENV=development
      - APP_DATABASE_URL=mysql://mysql_root:mysql_pass@mariadb/odiometro
      - APP_DATABASE_USER=mysql_root
      - APP_DATABASE_PASSWORD=mysql_pass
      - APP_DATABASE_NAME=odiometro
      - APP_DATABASE_HOST=mariadb

      - SKIP_DB_WAIT=0
      - SKIP_DB_MIGRATION=0
      - SKIP_NPM_INSTALL=0
      - SKIP_BOWER_INSTALL=0
    build:
      context: .
      dockerfile: Dockerfile-app
    depends_on:
      - mariadb
    ports:
      - 3000:3000
    volumes:
      - .:/app