---
version: '2'

services:
  mariadb:
    tty: true
    environment:
      # - ALLOW_EMPTY_PASSWORD=yes
      # - MYSQL_DATABASE=${APP_BOT_NAME}
      # set default credentials
      # - MYSQL_ROOT_USER=mysql_root
      # - MYSQL_ROOT_PASSWORD=mysql_pass
      - MYSQL_ROOT_USER="mysql_root"
      - MYSQL_ROOT_PASSWORD="mysql_pass"
      - INIT_DB_NAMES="odiometro,amorometro"
    build:
      context: .
      dockerfile: Dockerfile-mariadb
    volumes:
      # Bitnami image supports docker-entrypoint-initdb.d/ to load .sql or .sh,
      # but it needs to be mounted as volume before the build starts
      # - ./db:/docker-entrypoint-initdb.d
      # Backup databases to host machine
      # - ./var/mysql:/bitnami/mariadb
      # Cache apt-get (for debug purposes)
      - ./var/apt/cache:/var/cache/apt/archives

  express:
    tty: true  # Enables debugging capabilities when attached to this container.
    environment:
      - PORT=3000
      - NODE_ENV=development
      # - APP_DATABASE_URL=mysql://mysql_root:mysql_pass@mariadb/odiometro
      # - APP_BOT_NAME=${APP_BOT_NAME}
      - APP_DATABASE_NAME=${APP_BOT_NAME}
      - APP_DATABASE_HOST=mariadb
      - APP_DATABASE_USER=mysql_root
      - APP_DATABASE_PASSWORD=mysql_pass
    working_dir: /home/node/app
    build: .
    depends_on:
      - mariadb
    ports:
      - 3000:3000
    volumes:
      - .:/app
