version: '2'

services:
  mariadb:
    tty: true
    image: 'docker.io/bitnami/mariadb:10.3-debian-10'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_DATABASE=odiometro
      # set default credentials
      - MARIADB_ROOT_USER=mysql_root
      - MARIADB_ROOT_PASSWORD=mysql_pass
    build:
      context: ../
      dockerfile: docker/Dockerfile-mariadb

  express:
    tty: true # Enables debugging capabilities when attached to this container.
    image: docker.io/bitnami/express:4-debian-10
    environment:
      - PORT=3000
      - NODE_ENV=development
      # - APP_DATABASE_URL=mysql://mysql_root:mysql_pass@mariadb/odiometro
      - APP_DATABASE_USER=mysql_root
      - APP_DATABASE_PASSWORD=mysql_pass
      - APP_DATABASE_NAME=odiometro
      - APP_DATABASE_HOST=mariadb
      # Skip fetching dependencies and database migrations for production image
      - SKIP_DB_WAIT=0
      - SKIP_DB_MIGRATION=0
      # enable/disable features
      - SKIP_NPM_INSTALL=0
      - SKIP_BOWER_INSTALL=1
      - SKIP_SAMPLE_CODE=1
    build:
      context: ../
      dockerfile: docker/Dockerfile-app
    depends_on:
      - mariadb
    ports:
      - 3000:3000
    volumes:
      - ..:/app
